//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rentacarEntities : DbContext
    {
        public rentacarEntities()
            : base("name=rentacarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<announcements> announcements { get; set; }
        public virtual DbSet<cars> cars { get; set; }
        public virtual DbSet<reservations> reservations { get; set; }
        public virtual DbSet<admins> admins { get; set; }
    }
}
